/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ESFOT
 */
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Herencia extends javax.swing.JFrame {

    /**
     * Creates new form Herencia
     */
    public Herencia() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHola = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        btnOkey = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel4.setText("jLabel4");

        lblTexto.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hola Mundo");

        lblHola.setText("Escribe");

        btnOkey.setText("ok");
        btnOkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkey)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkey, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHola))
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeyActionPerformed
       
        //ejemplo2
      /*ArrayList list=new ArrayList();
      list.add("Hola");
      list.add(1);
      
        System.out.println("posicion 0 "+list.get(0));       
       System.out.println("posciion 1"+list.get(1));
         */
        
      //ejemplo3
      
      int opcion=JOptionPane.showConfirmDialog(rootPane, " esta seguro","confirmacion ",JOptionPane.OK_CANCEL_OPTION ,JOptionPane.WARNING_MESSAGE);
      
     
      if(opcion==0){
          
          String txt=txtTexto.getText();
          this.list.add(txt);
          OptionPane.showMessageDialog(rootPane, txt,"mensaje",JOptionPane.ERROR_MESSAGE);
     
          for(Object itewm :list){
              txtItems.setText((String)item)
                      }           
      }else{
      OptionPane.showMessageDialog(rootPane,"el item se ",JOptionPane.ERROR_MESSAGE);
         
          }
      
      //eje mplo1
      /*  String txt= txtTexto.getText() ;
      
      //solo muestra mensajes al ususario No devuelve  nada
     // JOptionPane.showMessageDialog(rootPane, txt,"mensaje",JOptionPane.ERROR_MESSAGE);
      
      //este no s devuelve un entero
      
      int opcion=JOptionPane.showConfirmDialog(rootPane, " esta seguro","confirmacion ",JOptionPane.OK_CANCEL_OPTION ,JOptionPane.WARNING_MESSAGE);
      
      
      if(opcion==0){
          lblHola.setText(txt);
          
      }else
          if(opcion==1){
              lblHola.setText(" ");
          }
     
      
      
      
     JOptionPane.showInputDialog("ingrese el mensaje");
     String opc[]=new String [3];
     opc[0]="uno";
     opc[1]="dos";
     opc[2]="tres";
     opc[3]="4";
     
     int se= JOptionPane.showOptionDialog(rootPane, "Mensaje", "titulo", JOptionPane.YES_NO_OPTION, HEIGHT, JOptionPane.INFORMATION_MESSAGE, null, opc, opc[0]);
     
      System.out.println("Selecciono:"+se);
     */ 
      
      
  
    }//GEN-LAST:event_btnOkeyActionPerformed

    
   
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Herencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkey;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblHola;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
